//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFAplicationsMedical.WCFServiceCliente {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/WCFServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string des_ape_maternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string des_ape_paternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string des_direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string des_distritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string des_emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string des_nombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fec_nacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ind_estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int num_telefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_cliente {
            get {
                return this.cod_clienteField;
            }
            set {
                if ((this.cod_clienteField.Equals(value) != true)) {
                    this.cod_clienteField = value;
                    this.RaisePropertyChanged("cod_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string des_ape_materno {
            get {
                return this.des_ape_maternoField;
            }
            set {
                if ((object.ReferenceEquals(this.des_ape_maternoField, value) != true)) {
                    this.des_ape_maternoField = value;
                    this.RaisePropertyChanged("des_ape_materno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string des_ape_paterno {
            get {
                return this.des_ape_paternoField;
            }
            set {
                if ((object.ReferenceEquals(this.des_ape_paternoField, value) != true)) {
                    this.des_ape_paternoField = value;
                    this.RaisePropertyChanged("des_ape_paterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string des_direccion {
            get {
                return this.des_direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.des_direccionField, value) != true)) {
                    this.des_direccionField = value;
                    this.RaisePropertyChanged("des_direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string des_distrito {
            get {
                return this.des_distritoField;
            }
            set {
                if ((object.ReferenceEquals(this.des_distritoField, value) != true)) {
                    this.des_distritoField = value;
                    this.RaisePropertyChanged("des_distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string des_email {
            get {
                return this.des_emailField;
            }
            set {
                if ((object.ReferenceEquals(this.des_emailField, value) != true)) {
                    this.des_emailField = value;
                    this.RaisePropertyChanged("des_email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string des_nombres {
            get {
                return this.des_nombresField;
            }
            set {
                if ((object.ReferenceEquals(this.des_nombresField, value) != true)) {
                    this.des_nombresField = value;
                    this.RaisePropertyChanged("des_nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fec_nacimiento {
            get {
                return this.fec_nacimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.fec_nacimientoField, value) != true)) {
                    this.fec_nacimientoField = value;
                    this.RaisePropertyChanged("fec_nacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ind_estado {
            get {
                return this.ind_estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ind_estadoField, value) != true)) {
                    this.ind_estadoField = value;
                    this.RaisePropertyChanged("ind_estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int num_telefono {
            get {
                return this.num_telefonoField;
            }
            set {
                if ((this.num_telefonoField.Equals(value) != true)) {
                    this.num_telefonoField = value;
                    this.RaisePropertyChanged("num_telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/WCFServices.Errores")]
    [System.SerializableAttribute()]
    public partial class RepetidoException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFServiceCliente.IClientes")]
    public interface IClientes {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientes/CrearCliente", ReplyAction="http://tempuri.org/IClientes/CrearClienteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFAplicationsMedical.WCFServiceCliente.RepetidoException), Action="http://tempuri.org/IClientes/CrearClienteRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/WCFServices.Errores")]
        WCFAplicationsMedical.WCFServiceCliente.Cliente CrearCliente(WCFAplicationsMedical.WCFServiceCliente.Cliente clienteACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientes/CrearCliente", ReplyAction="http://tempuri.org/IClientes/CrearClienteResponse")]
        System.Threading.Tasks.Task<WCFAplicationsMedical.WCFServiceCliente.Cliente> CrearClienteAsync(WCFAplicationsMedical.WCFServiceCliente.Cliente clienteACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientes/ObtenerCliente", ReplyAction="http://tempuri.org/IClientes/ObtenerClienteResponse")]
        WCFAplicationsMedical.WCFServiceCliente.Cliente ObtenerCliente(int cod_cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientes/ObtenerCliente", ReplyAction="http://tempuri.org/IClientes/ObtenerClienteResponse")]
        System.Threading.Tasks.Task<WCFAplicationsMedical.WCFServiceCliente.Cliente> ObtenerClienteAsync(int cod_cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientes/ListarClientes", ReplyAction="http://tempuri.org/IClientes/ListarClientesResponse")]
        WCFAplicationsMedical.WCFServiceCliente.Cliente[] ListarClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientes/ListarClientes", ReplyAction="http://tempuri.org/IClientes/ListarClientesResponse")]
        System.Threading.Tasks.Task<WCFAplicationsMedical.WCFServiceCliente.Cliente[]> ListarClientesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientesChannel : WCFAplicationsMedical.WCFServiceCliente.IClientes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientesClient : System.ServiceModel.ClientBase<WCFAplicationsMedical.WCFServiceCliente.IClientes>, WCFAplicationsMedical.WCFServiceCliente.IClientes {
        
        public ClientesClient() {
        }
        
        public ClientesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFAplicationsMedical.WCFServiceCliente.Cliente CrearCliente(WCFAplicationsMedical.WCFServiceCliente.Cliente clienteACrear) {
            return base.Channel.CrearCliente(clienteACrear);
        }
        
        public System.Threading.Tasks.Task<WCFAplicationsMedical.WCFServiceCliente.Cliente> CrearClienteAsync(WCFAplicationsMedical.WCFServiceCliente.Cliente clienteACrear) {
            return base.Channel.CrearClienteAsync(clienteACrear);
        }
        
        public WCFAplicationsMedical.WCFServiceCliente.Cliente ObtenerCliente(int cod_cliente) {
            return base.Channel.ObtenerCliente(cod_cliente);
        }
        
        public System.Threading.Tasks.Task<WCFAplicationsMedical.WCFServiceCliente.Cliente> ObtenerClienteAsync(int cod_cliente) {
            return base.Channel.ObtenerClienteAsync(cod_cliente);
        }
        
        public WCFAplicationsMedical.WCFServiceCliente.Cliente[] ListarClientes() {
            return base.Channel.ListarClientes();
        }
        
        public System.Threading.Tasks.Task<WCFAplicationsMedical.WCFServiceCliente.Cliente[]> ListarClientesAsync() {
            return base.Channel.ListarClientesAsync();
        }
    }
}
